=== caoanhquan-qn/XML-and-XMLSchema/patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Patient" xmlns:tns="http://www.example.org/Patient" elementFormDefault="qualified">
    <element name="Patient" type="tns:Patient" />
    <complexType name="Patient">
        <sequence>
            <element name="name" type="tns:String15Chars"></element>
            <element name="age" type="int"></element>
            <element name="email" type="string" minOccurs="0"></element>
            <element name="gender" type="tns:Gender"></element>
            <element name="phone" type="string" maxOccurs="3"></element>
            <element name="PaymentType" type="tns:PaymentType"></element>
        </sequence>
    </complexType>
    <complexType name="PaymentType">
        <choice>
            <element name="cash" type="decimal" />
            <element name="insurance" type="tns:Insurance" />

        </choice>

    </complexType>
    <complexType name="Insurance">
        <all>
            <element name="limit" type="decimal" />
            <element name="provider" type="string" />
        </all>
    </complexType>
    <simpleType name="String15Chars">
        <restriction base="string">
            <maxLength value="15"></maxLength>
        </restriction>
    </simpleType>
    <simpleType name="Gender">
        <restriction base="string">
            <enumeration value="Male" />
            <enumeration value="Female" />
        </restriction>
    </simpleType>
</schema>

=== caoanhquan-qn/XML-and-XMLSchema/PatientSchema/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Patient ID="302563"
	xmlns:tns="http://www.example.org/Patient"
	xmlns:tns1="http://www.example.org/Common"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Patient Patient.xsd ">
	<tns:name>Nick</tns:name>
	<tns:age>31</tns:age>
	<tns:gender>Male</tns:gender>
	<tns:phone>0424506789</tns:phone>
	<tns:PaymentType>
		<!-- <tns:cash>3000</tns:cash> -->
		<tns:insurance>
			<tns:limit>4000</tns:limit>
			<tns:provider>Bupa</tns:provider>
		</tns:insurance>
	</tns:PaymentType>
</tns:Patient>
